# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]

# Setup
title:            DBremont
tagline:          'My Personal Blog'
description:      "Hello! I'm Daniel Victoriano Bremont. Welcome to my blog."
url:              https://blog.dbremont.dev/
baseurl:          /
plugins: [jekyll-paginate]
excerpt_separator: <!--more-->


author:
  name:           'Daniel Victorino Bremont'
  url:            https://blog.dbremont.dev/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
