# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

gems: [jekyll-paginate]

# Setup
title:            DanielLog
tagline:          'Mi Log/Blog Personal'
description:      "Hola!, bienvenidos a mi log-blog."
url:              https://blog.dbremont.dev/
baseurl:          /
excerpt_separator: <!--more-->

author:
  name:           'Daniel Victorino Bremont'
  url:            https://blog.dbremont.dev/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
