# Dependencies
# markdown:       redcarpet
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

gems: [jekyll-paginate]

# Setup
title:            DBremont
tagline:          'My Personal Blog'
description:      "Hello! I'm Daniel Victoriano Bremont. Welcome to my blog."
url:              https://blog.dbremont.dev/
baseurl:          /home
plugins: [jekyll-paginate]


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
